open_system('gm_broadwayIPC_2024b');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_broadwayIPC_2024b/conv_core/Delay11', 'user1');
annotate_port('gm_broadwayIPC_2024b/conv_core/Delay11', 1, 1, 'cp : 6.307 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_broadwayIPC_2024b/conv_core/Delay8', 'user1');
annotate_port('gm_broadwayIPC_2024b/conv_core/Delay8', 0, 1, 'cp : 0.511 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_broadwayIPC_2024b/conv_core/Product', 'user2');
annotate_port('gm_broadwayIPC_2024b/conv_core/Product', 0, 1, 'cp : 6.065 ns');
