open_system('gm_broadwayIPC_2024b');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_broadwayIPC_2024b/conv_core/Delay4', 'user1');
annotate_port('gm_broadwayIPC_2024b/conv_core/Delay4', 0, 1, 'cp : 0.511 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_broadwayIPC_2024b/conv_core/Delay7', 'user1');
annotate_port('gm_broadwayIPC_2024b/conv_core/Delay7', 1, 1, 'cp : 3.083 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_broadwayIPC_2024b/conv_core/Shift Arithmetic4', 'user2');
annotate_port('gm_broadwayIPC_2024b/conv_core/Shift Arithmetic4', 0, 1, 'cp : 0.753 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_broadwayIPC_2024b/conv_core/Sum_stage2', 'user2');
annotate_port('gm_broadwayIPC_2024b/conv_core/Sum_stage2', 0, 1, 'cp : 1.768 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_broadwayIPC_2024b/conv_core/Sum_stage3', 'user2');
annotate_port('gm_broadwayIPC_2024b/conv_core/Sum_stage3', 0, 1, 'cp : 2.841 ns');
